/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pl.exsio.querydsl.entityql;

import org.gradle.api.Project;
import org.gradle.api.internal.project.ProjectInternal;
import org.gradle.internal.impldep.org.junit.rules.TemporaryFolder;
import org.gradle.testfixtures.ProjectBuilder;
import org.junit.Test;

import java.io.File;
import java.nio.file.Files;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;


public class GeneratePluginTest {

    @Test
    public void pluginRegistersATask() {
        //when:
        Project project = ProjectBuilder.builder().build();
        project.getPlugins().apply("pl.exsio.querydsl.entityql");

        //then:
        assertThat(project.getTasks().findByName("generateModels")).isNotNull();
    }


    @Test
    public void pluginRegistersATaskWithConfiguration() throws Exception {

        //given:
        TemporaryFolder testProjectDir = new TemporaryFolder();
        testProjectDir.create();
        File buildFile = testProjectDir.newFile("build.gradle");
        Files.write(buildFile.toPath(), ("entityql {generators=[\n" +
                "generator={\n" +
                "type='JPA'\n" +
                "sourcePackage='pl.exsio.querydsl.entityql'\n" +
                "destinationPackage='pl.exsio.querydsl.entityql.generated'}\n" +
                "]\n" +
                "}").getBytes());

        Project project = ProjectBuilder.builder()
                .withProjectDir(testProjectDir.getRoot())
                .build();

        //when:
        project.getPlugins().apply("pl.exsio.querydsl.entityql");
        ((ProjectInternal) project).evaluate();
        GenerateTask task = (GenerateTask) project.getTasks().findByName("generateModels");
        List<Generator> generators = task.getGenerators();

        //then:
        assertThat(generators).isNotNull();
        assertThat(generators.size()).isEqualTo(1);
        assertThat(generators.get(0).getType()).isEqualTo(Generator.Type.JPA);
        assertThat(generators.get(0).getSourcePackage()).isEqualTo("pl.exsio.querydsl.entityql");
        assertThat(generators.get(0).getDestinationPackage()).isEqualTo("pl.exsio.querydsl.entityql.generated");
        testProjectDir.delete();
    }
}
